name: Add Raw Assets to Existing Release
on:
  push:
    tags:
      - 'v0.2.0-beta'

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Upload Root Files to Existing Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v0.2.0-beta'
          files: |
            main.js
            manifest.js
            styles.css
