name: Add Raw Assets to New Release
on:
  push:
    tags:
      - 'v0.2.1'

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Upload Root Files to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'v0.2.1'
          files: |
            main.js
            manifest.js
            styles.css